#!/bin/sh
# chkconfig: - 84 16
# description:  Perl FastCGI Process Daemon
# processname: perl-fcgi
# perl daemon: /usr/bin/fastcgi-wrapper.pl
#
### BEGIN INIT INFO
# Provides: perl-fcgi
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: start and stop Perl FCGI
# Description: Perl FastCGI Daemon
### END INIT INFO

# Standard LSB functions
#. /lib/lsb/init-functions

# Source function library.
. /etc/init.d/functions

# Check that networking is up.
. /etc/sysconfig/network

#
user="nginx"
prog="perl-fcgi"
wrapper="/usr/bin/fastcgi-wrapper.pl"

#
pidfile="/var/run/${prog}/${prog}.pid"
lockfile="/var/lock/subsys/${prog}"
rc=0

start () {
    if [[ -e ${lockfile} ]];
    then
        pid=$(pidofproc -p ${pidfile} ${prog})
        echo "$prog (pid ${pid}) is already running..."
        rc=2
    else
        echo -n $"Starting $prog: "
        dir=$(dirname ${pidfile})
        [ -d $dir ] || mkdir $dir
        daemon --pidfile ${pidfile} --user ${user} ${wrapper}
        rc=$?
        echo
        [ $rc -eq 0 ] && pidofproc ${wrapper} > ${pidfile} && touch ${lockfile}
    fi
}
stop () {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} ${prog}
    rc=$?
    echo
    if [ $rc -eq 0 ] ; then
        rm -f ${lockfile} ${pidfile}
    fi
}
restart () {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status -p ${pidfile} ${prog}
    rc=$?
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    rc=2
    ;;
esac

exit $rc
